### PR TITLE
Native Messaging to launch Firefox and check if Firefox is installed

### LINKED ISSUE #50: [Chromium] No error block displayed on welcome page when Firefox is not installed
**Description:**
According to the spec doc, if Firefox is not installed, the welcome page should display an error block informing users that Firefox is not installed. Furthermore, this error block should also provide an installation link and instructions on how to install Firefox.

Currently, this error block is not displayed/implemented.

**Preconditions:**
1. Ensure Firefox is not installed.

**Steps to reproduce:**
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. The welcome page opens in a new tab
3. Notice that the error block informing the user that Firefox is not installed is not currently displayed on the welcome page.

**Expected:**
As per the spec doc, an error block informing the user that Firefox is not installed should be displayed on the welcome page. This error block should also contain an installation link and instructions on how to install Firefox.

**Actual:**
The error block is not displayed when Firefox is not installed.

### LINKED ISSUE #54: [Chromium] Clicking toolbar button when Firefox is not installed does nothing, but according to the spec doc it should open the welcome page
**Description:**
Clicking the toolbar button when Firefox is not installed will do nothing, instead of opening the welcome page as per the spec doc.

**Preconditions:**
1. Ensure Firefox is not installed.

**Steps to reproduce:**
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Access https://www.wikipedia.org/ in a new tab
3. Click the toolbar button
4. Notice nothing happens instead of the welcome page opening

**Expected:**
As per the spec doc, when Firefox is not installed, clicking the toolbar button should open the welcome page.

**Actual:**
Clicking the toolbar button when Firefox is not installed does nothing.

### LINKED ISSUE #79: [macOS][Chromium] Unable to launch file:/// pages in Firefox
Description:
As per the spec docs the extension allows users to open file:/// pages in Firefox, however, the file:/// page does not load in Firefox as expected, on macOS.

Once Firefox is launched or gets focused, a new tab page is displayed instead of the launched file:/// page, which actually belongs to a new Firefox window that just opened.

**Note 1:** Yesterday (02.22.2024) I’m most certainly it worked i.e. I was able to launch file:/// pages in Firefox Nightly.

**Note 2:** Today (02.23.2024), I started uninstalling the different Firefox versions I had installed, after checking if I can launch the file:/// page in them and this is what I observed:
- the Chromium extension by default launched Nightly, which is affected by the issue so I uninstalled Nightly.
- Since I uninstalled Nightly, the next browser that was launched by default became Beta Developer Edition. On this browser I did manage to launch the file:/// page into it, however only once. Now I’m not sure if the browser upon launching/closing got updated or not and that might have caused the issue. I uninstalled Beta Developer Edition
- next in line was Firefox Release which exhibited the same issue as the other Firefox browsers.

**Note 3:** Doing the reverse, launching a file:/// page from Firefox to a Chromium browser works.

**Note 4:** Once the Firefox browser launches, checking the browser console shows the following:

```
Error: Firefox and Firefox-private protocols can only be used in conjunction with http and https urls. BrowserContentHandler.sys.mjs:1390:15

    handleFirefoxProtocol resource:///modules/BrowserContentHandler.sys.mjs:102
    resolveURIInternal resource:///modules/BrowserContentHandler.sys.mjs:116
    dch_handle resource:///modules/BrowserContentHandler.sys.mjs:1367
    dch_handle resource:///modules/BrowserContentHandler.sys.mjs:1390
```

**Note 5:** On Windows the issue does not occur.

Preconditions:
1. Access, for example, https://www.facebook.com/ and save the page on the computer so as to provide the file:/// page to be opened in Firefox.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the Chromium browser
2. Load the previously saved Facebook page
3. Click the toolbar button to launch the page into Firefox
4. Notice that the page is not displayed in Firefox, instead, a new tab page is shown
5. Open the browser console on Firefox and see the error mentioned in Note (4) above

Expected:
The file:/// page launched from the Chromium browser should load in Firefox, as in the case of Windows.

Actual:
The file:/// page is not launched in Firefox.

### PR DESCRIPTION
**Pull request by GregSherman**
Fixes #79 
Fixes #54 
Fixes #50 

[Native Messaging document](https://docs.google.com/document/d/1I1WY5lV62zDy86CCceBXdQm-4PL18VKvXy8p6UmuA7g/edit)

This patch has 2 related changes. First, `isFirefoxInstalled()` is replaced by `getInstalledFirefoxVariant()` which uses native messaging to determine which firefox variant of Dev, Nightly, Release, ESR, is installed in that order with an early return if so. The return value is the native messaging host name to be used within `launchBrowser()`. This is where the extension commands the variant of firefox to open the url in normal or private mode.

### CODE REVIEW

File: src/chromium/interfaces/getters.js [hunk 1]
```diff
@@ -1,19 +1,29 @@
 import { getExternalBrowser } from "Shared/backgroundScripts/getters.js";
 
+const nativeApps = [
+  "org.mozilla.firefox_bridge_nmh_dev",
```
Comment (Rob--W) [inline src/chromium/interfaces/getters.js:4]: Let's do this order:
- release
- nightly
- esr
- dev

Then the most commonly installed flavor is found first.

File: src/chromium/interfaces/getters.js [hunk 2]
```diff
@@ -1,19 +1,29 @@
...
-export async function getIsFirefoxInstalled() {
-  // NOTE: We are not currently handling the case where Firefox is not installed until
-  // native messaging is implemented. We will assume for now that Firefox is always installed.
-  const result = await browser.storage.session.get("isFirefoxInstalled");
-  if (result.isFirefoxInstalled === undefined) {
-    browser.storage.session.set({ isFirefoxInstalled: true });
-    return true;
+export async function getInstalledFirefoxVariant() {
+  // Check for installed variants using the respective native messaging host.
+  for (const nativeApp of nativeApps) {
```
Comment (Rob--W) [inline src/chromium/interfaces/getters.js:18]: Is the latency acceptable?

If not, consider caching the result in the storage.session API.

A potential issue with caching the availability is that the availability of the browser may change at runtime. A way to counter that is to try the most recently found browser first.

File: src/chromium/interfaces/getters.js (hunk 1 above)
Comment (GregSherman) [reply src/chromium/interfaces/getters.js:4]: In the attached document, under "Different Firefox channel", it says to use this order. I believe it's because users who have two or more releases, they likely use the more "dev-ier" one.

File: src/chromium/interfaces/launchBrowser.js [hunk 3]
```diff
@@ -1,33 +1,51 @@
...
+      : "LaunchFirefox";
+    const response = await browser.runtime.sendNativeMessage(
+      nativeMessagingHost,
+      {
+        command,
+        data: { url },
+      },
+    );
+
+    if (response.result_code === 1) {
```
Comment (willdurand) [inline src/chromium/interfaces/launchBrowser.js:39]: In general I would check for anything other than success code (which should be `0`) instead of comparing `result_code` with _a_ non-success value. If the app on the other side starts to support other error codes, things might break here.

```suggestion
    if (response.result_code !== 0) {
```

File: src/chromium/interfaces/getters.js (hunk 2 above)
Comment (GregSherman) [reply src/chromium/interfaces/getters.js:18]: It appears like it is. How would I figure this out? Populating this list with 100 nmhs still remains instantaneous.

File: src/chromium/interfaces/getters.js (hunk 1 above)
Comment (mhughes-mozilla) [reply src/chromium/interfaces/getters.js:4]: > Let's do this order:
> 
>     * release
> 
>     * nightly
> 
>     * esr
> 
>     * dev
> 
> 
> Then the most commonly installed flavor is found first.

My thinking was based on user deliberate actions. A developer is most likely to use and test a dev build they did locally. Someone using nightly is doing so deliberately regardless of if they have a release build installed. And we should prefer newer versions of everything over ESR if a newer version is installed.

If the user wants to use release, they can likely more easily delete the dev or nightly build, if they use multiple channels at once. If they don't use multiple channels, it doesn't matter.

Rob, do you have any data to indicate users are more likely to want the release build channel to be the first one that should be connected with?

This should really be user configurable in some way. For the next iteration, we can add a configurable setting in the Chromium extension. For now, any order (including the one Greg has already done) should be fine to commit, as long as we communicate it to users when we make this available.

File: src/chromium/interfaces/getters.js (hunk 2 above)
Comment (mhughes-mozilla) [reply src/chromium/interfaces/getters.js:18]: What Rob suggests is probably for the best:

```
let previousNativeApp = await browser.settings.local.get("WHATEVER");

const isValid = async (nativeApp) => {
  try {
    await browser.runtime.sendNativeMessage(nativeApp, {command: "GetVersion",});
    return true;
  } catch (err) {
    return false;
  }
};

if (await isValid(previousNativeApp)) {
  return previousNativeApp;
}

// Check for installed variants using the respective native messaging host.
for (const nativeApp of nativeApps) {
  if (await isValid(nativeApp)) {
    await browser.settings.local.set("...", nativeApp);
    return nativeApp;
  }
}

return undefined;
```

**Comment by GregSherman** [comment]
In addition to the above changes, added in a new ping for a browser launch failure that occurs within a valid NMH. See a sample [ping here](https://debug-ping-preview.firebaseapp.com/pings/firefox-bridge/0331c98f-2df8-4ff4-b146-e94c9170966a). This fails due to an incorrect command.

File: metrics.yaml [hunk 4]
```diff
@@ -175,6 +175,27 @@ launch_event:
...
+    type: event
+    lifetime: ping
+    description: |
+      The browser did not launch due to a native messaging host fault. (Chromium Only)
+    bugs:
+      - https://linktobugs.page
+    data_reviews:
+      - https://linktodatareviews.page
+    notification_emails:
+      - gsherman@mozilla.com
```
Comment (mhughes-mozilla) [inline metrics.yaml:188]: I'll try to figure out who this should go to. It's not you Greg :)

File: metrics.yaml [hunk 5]
```diff
@@ -175,6 +175,27 @@ launch_event:
...
         type: string
+  failed_browser_launch:
+    type: event
+    lifetime: ping
+    description: |
+      The browser did not launch due to a native messaging host fault. (Chromium Only)
+    bugs:
+      - https://linktobugs.page
+    data_reviews:
+      - https://linktodatareviews.page
```
Comment (mhughes-mozilla) [inline metrics.yaml:186]: We should put something good in these links.
For the bugs, can you link to the main bug for this? Did we log one yet? All of the entries should link to the main tracking bug.

File: src/chromium/interfaces/launchBrowser.js [hunk 6]
```diff
@@ -1,33 +1,57 @@
...
     return false;
   }
 
-  if (!(await getIsFirefoxInstalled())) {
-    browser.tabs.create({ url: "https://www.mozilla.org/firefox/" });
+  const nativeMessagingHost = await getInstalledFirefoxVariant();
+  if (!nativeMessagingHost) {
+    // No Firefox variant is installed. Direct the user to the Firefox download page.
+    await browser.tabs.create({
+      url: "https://www.mozilla.org/firefox/new/",
```
Comment (mhughes-mozilla) [inline src/chromium/interfaces/launchBrowser.js:22]: Did you mean to use welcomePageNoExternalBrowserErrorChromium here?
I can't see what that localized value is used and it does match here.

**Review by mhughes-mozilla — CHANGES_REQUESTED** [review]

File: metrics.yaml (hunk 5 above)
Comment (GregSherman) [reply metrics.yaml:186]: I think the GitHub issue for data review would be the link here. For the others, I'm not sure what to put. Should probably figure them all out before changing anything

Comment (mhughes-mozilla) [reply metrics.yaml:186]: Can we just use that link for all of them?
If you don't think that's a good fit, then we can check with Amir for a link to whatever doc should be linked to for this.

File: src/chromium/interfaces/launchBrowser.js (hunk 6 above)
Comment (GregSherman) [reply src/chromium/interfaces/launchBrowser.js:22]: That value is used solely in the welcome page for the text inside the error notification. Right here, it seems that I missed the change in the [spec 1.5.4](https://docs.google.com/document/d/1jTxG4kyDsgwAVHYkDvHvABmO85-wk9vppJe6ikNe76A/edit#heading=h.dfbjsayo38mn) that if the user attempts to launch the browser with none installed it redirects to the welcome page. It used to say to launch the firefox install page.

File: metrics.yaml [hunk 7]
```diff
@@ -175,6 +175,27 @@ launch_event:
...
+    notification_emails:
+      - gsherman@mozilla.com
+    expires: never
+    extra_keys:
+      command:
+        description: The command used within the NMH. LaunchFirefox/LaunchFirefoxPrivate
+      native_messaging_host:
+        description: The NMH that was used to launch the browser
```
Comment (mhughes-mozilla) [inline metrics.yaml:194]: This should probably be a little more explanatory.

"The id of the NMH used to launch the browser, which equates to the build channel and only to the build channel."

With what it says there, my first read was that it could include the path to the browser executable, which is not data we should be tracking. Clarifying in the description might lead to fewer explanations about us tracking data we don't need to.

**Review by willdurand — COMMENTED** [review]
This looks good to me but there are still unresolved comments.

File: metrics.yaml (hunk 5 above)
Comment (GregSherman) [reply metrics.yaml:186]: Resolving for future patch: determining all glean fields

**Comment by GregSherman** [comment]
> This looks good to me but there are still unresolved comments.

They have been resolved, just marked them now.
